/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test.proto */

#ifndef PROTOBUF_C_test_2eproto__INCLUDED
#define PROTOBUF_C_test_2eproto__INCLUDED

#include "protobuf-c/protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _HgBleMsgPack HgBleMsgPack;


/* --- enums --- */


/* --- messages --- */

struct  _HgBleMsgPack
{
  ProtobufCMessage base;
  /*
   * bytes mac = 1;
   * sint32 rssi = 2;
   * bytes raw = 3;
   */
  int64_t timestamp;
};
#define HG_BLE_MSG_PACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hg_ble_msg_pack__descriptor) \
    , 0 }


/* HgBleMsgPack methods */
void   hg_ble_msg_pack__init
                     (HgBleMsgPack         *message);
size_t hg_ble_msg_pack__get_packed_size
                     (const HgBleMsgPack   *message);
size_t hg_ble_msg_pack__pack
                     (const HgBleMsgPack   *message,
                      uint8_t             *out);
size_t hg_ble_msg_pack__pack_to_buffer
                     (const HgBleMsgPack   *message,
                      ProtobufCBuffer     *buffer);
HgBleMsgPack *
       hg_ble_msg_pack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hg_ble_msg_pack__free_unpacked
                     (HgBleMsgPack *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*HgBleMsgPack_Closure)
                 (const HgBleMsgPack *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor hg_ble_msg_pack__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_test_2eproto__INCLUDED */
