/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "test.pb-c.h"
void   hg_ble_msg_pack__init
                     (HgBleMsgPack         *message)
{
  static const HgBleMsgPack init_value = HG_BLE_MSG_PACK__INIT;
  *message = init_value;
}
size_t hg_ble_msg_pack__get_packed_size
                     (const HgBleMsgPack *message)
{
  assert(message->base.descriptor == &hg_ble_msg_pack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hg_ble_msg_pack__pack
                     (const HgBleMsgPack *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hg_ble_msg_pack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hg_ble_msg_pack__pack_to_buffer
                     (const HgBleMsgPack *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hg_ble_msg_pack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HgBleMsgPack *
       hg_ble_msg_pack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HgBleMsgPack *)
     protobuf_c_message_unpack (&hg_ble_msg_pack__descriptor,
                                allocator, len, data);
}
void   hg_ble_msg_pack__free_unpacked
                     (HgBleMsgPack *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hg_ble_msg_pack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hg_ble_msg_pack__field_descriptors[1] =
{
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(HgBleMsgPack, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hg_ble_msg_pack__field_indices_by_name[] = {
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange hg_ble_msg_pack__number_ranges[1 + 1] =
{
  { 4, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hg_ble_msg_pack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HgBleMsgPack",
  "HgBleMsgPack",
  "HgBleMsgPack",
  "",
  sizeof(HgBleMsgPack),
  1,
  hg_ble_msg_pack__field_descriptors,
  hg_ble_msg_pack__field_indices_by_name,
  1,  hg_ble_msg_pack__number_ranges,
  (ProtobufCMessageInit) hg_ble_msg_pack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
